### ISSUE TITLE
Better instructions for vim with +python3 support only

### ISSUE THREAD

**Issue by jefft** [tbabej/taskwiki#108]
Ubuntu 16.04's version of vim all come compiled with +python3 and -python, meaning it won't work with taskwiki. Googling for solutions is unproductive, with either outdated advice (installing 'vim-nox' or 'vim-gnome makes no difference) or bad advice (installing 'vim-nox-py2' remove python3 support, breaking other stuff).

If anyone knows a solution for installing on Ubuntu, it would be good to point to it in the README. If rewriting in python3 is an option that might be a good idea long-term.

**Comment by tbabej** [comment]
I am always trying to write the code in a Python3 compatible way, so this wasn't a lot of work. Mostly the issue was in trying to figure out how to force my vim to run under python3 :)

Long story short, I created WIP python3 branch `python3port` and I would be glad if you could test it (so far I haven't ported the test framework, that seems to have his own issues).

**Comment by jefft** [comment]
Great :) I'm afraid I can't test, as I'm totally unfamiliar with taskwarrior/taskwiki, and wouldn't know what 'working' looks like. Perhaps other actual users can try it out:

https://github.com/tbabej/taskwiki/tree/python3port

**Comment by tbabej** [comment]
Python3 support merged in master.
