### ISSUE TITLE
Can robgolding/tasklib-1.1.0 substitute tbabej/tasklib@develop?

### ISSUE THREAD

**Issue by crocket** [tbabej/taskwiki#137]
It seems robgolding/tasklib-1.1.0 and tbabej/tasklib@develop are almost identical.
robgolding/tasklib-1.1.0 is already available on a gentoo overlay.

**Comment by tbabej** [comment]
In the times of stability, tbabej@develop and latest released tasklib version contain the same code. That should be the case now.

In the past when taskwiki was rapidly developed, it often used features form tasklib which haven't been released yet, that's why README.md references tbabej@develop instead.

**Comment by crocket** [comment]
Which one between the two do you recommend for the future?

**Comment by tbabej** [comment]
If it is more convenient for you, just use tasklib 1.1.0. I don't see heavy development in tasklib happening any time soon.

**Comment by crocket** [comment]
Thanks. Closing it.
