### ISSUE TITLE
Workflow examples - how do you use taskwiki?

### ISSUE THREAD

**Issue by amitbeka** [tbabej/taskwiki#190]
Hi there,

First, thanks for the wonderful work and the helpful replies. This is not a regular issue, but more a request for comments.

I'm trying to use taskwiki with my current takwarrior/vimwiki setup, which includes 2 wikis (one personal, one work) and a lot of aliases in the shell for modifying and interacting with taskwarrior.

I'm trying to understand how people use taskwiki in general, and specifically when you have the command-line taskwarrior as another "endpoint". For example, if I mark a task as done in the command line, but I also have it in a viewport, it might return back to pending state if I'm not careful.
Another approach is to show also completed tasks in the viewport, but then the tasks keep piling up...

So, how do you use it? how do you structure your viewports and preset headers, if any? do you put all task in one file or you just put them around in their respective wiki pages (good for context)?

Thanks a lot for any comment,
Beka

**Comment by bodograumann** [comment]
The potential race condition is the reason I try not to mix using taskwiki and the task command concurrently for the same tasks. If you still have a task open in vim you need to reload (`:e`) the file to get changes introduced by `task` and if you accidentally save it (`:w`), the changes you introduced via the command line will get reverted.

I originally started out from text files containing my projects. Then I found vimwiki and that lead me to taskwiki. At first I did not really use the command line with it, but now I use it more and more, especially for simple or stand-alone tasks. On the other hand to combine the tasks with more information and have a proper task hierarchy, taskwiki is an invaluable tool.

I tend to put all tasks for one project into one taskwiki file and start with a simple viewport:
```
= My Project XYZ | proj:xyz status.not:completed =
* […]
```

Then later I might make that into a preset header and introduce more sections
```
= My Project XYZ || proj:xyz status.not:completed =

== General Things | -VISIBLE ==
* […]

== Bugs | +bug ==
* […]

== Feature Requests | +fr ==
* […]
```

In the end, there are a lot of ways to use taskwiki so it fits your specific needs. I love that flexibility.

**Comment by amitbeka** [comment]
Thanks for sharing :)

**Comment by liskin** [comment]
Hi,

I'm fairly new to taskwarrior and taskwiki so I'm not sure if the workflow I adopted will stay, but I encountered and solved similar problems so I'll comment about it here.

My wiki index page looks like this:

```
= To Do =

== today | @today | scheduled:today ==
* […]

== tomorrow | @tomorrow | scheduled:tomorrow ==
* […]

== orphan | project: -COMPLETED ==

= Projects =
* […]

= Notes =
* […]
```

A project page, then, contains (among other things like notes):

```
== To Do | project:xyz @todo+recent ==
* […]
```

`@today` shows tasks that I scheduled for today, are due today, or were done today (so I can see not only what's left but also what I already accomplished). `@tomorrow` is the plan for tomorrow. `@orphan` shows pending tasks without a project, as these would otherwise be lost if not planned. `@todo+recent` hides tasks that were finished some time ago (I'll tweak the exact delay as I go along). These are defined [here](https://github.com/liskin/dotfiles/blob/f441a1c6bcaf760ef73d37c3e6a108b7c1efdd6b/.taskrc#L22-L24).

As these filters depend on the current date, I need to refresh the viewports once a day. I also need to refresh them when the taskwarrior database is updated outside of taskwiki (as you both mentioned) and also when I add a task in one wiki page and then switch to a hidden buffer with another (the index with today's plan, for example), I need refresh as well. I could close vim when using taskwarrior and type :e after switching buffers (which reloads the entire python plugin, drops all caches and adds garbage to sys.path; fix [here](https://github.com/liskin/taskwiki/commit/4d9c64a232fbcd12fee80c5cd0836bf3eaf5082f)) but I had another idea:

Check if taskwiki needs refreshing every time I activate the vim window (FocusGained autocmd) or switch buffers (BufEnter). The [check](https://github.com/liskin/dotfiles/blob/f441a1c6bcaf760ef73d37c3e6a108b7c1efdd6b/.vim/after/ftplugin/vimwiki.vim#L7-L17) works by comparing the modifiation time of the wiki page against the modification time of timewarrior database, and also triggers whenever the wiki page hasn't yet been modified today (to refresh today's plan). Hasn't been battle tested yet but seems to work. It does require some fixes in taskwiki, however: https://github.com/liskin/taskwiki/commit/b33f5ca5753a01fa2b69ffa7d81699cc053513f2, https://github.com/liskin/taskwiki/commit/4b451b04dcbd14a965028c0681efa26c5f018f22, possibly also https://github.com/liskin/taskwiki/commit/4d9c64a232fbcd12fee80c5cd0836bf3eaf5082f, https://github.com/liskin/taskwiki/commit/ccbe00d9525be6586a590f4c51eda624ac5efd2a and https://github.com/liskin/taskwiki/commit/54c3bbc76b8acec7e6b329a37b3b4929581052c2. I'll be submitting these upstream once I get the tests working and once it's have been in regular use for a while.

**Comment by amitbeka** [comment]
Nice, thank you.

Since 2018 I already ditched taskwarrior for pure-vimwiki setup, I found out I have enough control without it.
