### ISSUE TITLE
inherited defaults

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#26]
With the ability to have defaults in headings and sub-headings, as long as the blocks are contiguous (same text-object) the defaults could be inherited. So for example;
<pre>
== Bake Sale | | project:bakesale == # this header has no filter, or list, but has default
=== Baked goods | project:bakesale +bake | +bake === # (also project:bakesale)
* [ ] pick recipes
* [ ] bla 
* [ ] bla 
==== Shop for ingredients | project:bakesale +shop | +shop === # (also +bake & project:bakesale)
* [ ] get flour
* [ ] get sugar
=== Labeling | project:bakesale +label | +label === # (also has project:bakesale)
* [ ] design labels
* [ ] print labels
</pre>
Maybe not the most exciting use-case, but just outlining the idea.

**Comment by tbabej** [comment]
I have been thinking about this too, and I believe the problem you're trying to solve is not having too much metadata in the header. I came to the conclusion that the correct solution to this problem is hiding the metadata, rather than having inherited for various reasons:

* performance
* it's better to be explicit, since we're talking about default values here
* implementation simplicity

Hiding of the metadata in the heading is already (just recently) implemented, so I consider this a solved issue.
