### ISSUE TITLE
new command TaskWikiColor

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#71]
a toggle, to enable or disable tw_colors in the current buffer.

**Comment by tbabej** [comment]
I don't think this is necessary. One can just change the setting and reopen the taskwiki file. This will be introducing a command which will be only used once (when user wants to determine if he will use TW colors, or not).

**Comment by linuxcaffe** [comment]
I guess I was thinking that the user might like colors on some instances, but not others. I think there might even be arguments for some ViewPorts to have tw_colors, and not others, but I'm not married to it :)

**Comment by tbabej** [comment]
Arguments? Let me hear them. Otherwise, I am not convinced.

**Comment by linuxcaffe** [comment]
Well for one thing, I'll bet tw_colors will trample any syntax highliting that vimwiki or markdown might show, like the :tag: hilight. A hypothetical user might prefer working with colors off (for example) but want to use tw_colors to check for certain conditions, like overdue, and then turn them off again.. convinced yet?

**Comment by tbabej** [comment]
Well, the tw-colors does not introduce new colors -> only sources color definitions for things that are syntax highlighted in taskwiki. Currently that's not much, only: active, deleted and completed task (sourced from color.active, color.deleted and color.completed TW options).

Since tw-colors does not introduce any new highlighting definitions, it cannot interfere with anything that taskwiki does not interfere with if it's not turned on. Anyways, even if it did, it would be considered a bug, not an argument for adding an arbitrary command for turning it off and on again.

I get a little bit of sense out of this with your idea of "using colors to see overdue tasks only sometimes" - but that's really not related to tw-colors mode. It's not a blessing that will copy colors for all the states of tasks from TW. For the overdue task to be syntax highlighted, there would need to be a metadata flag on the line which would represent the 'overdueiness'. Which I am hesitant to introduce for this marginal benefit right now.

**Comment by tbabej** [comment]
Color highlighting for active, completed and deleted tasks work only because there's a corresponding character in the [ ] part of the task, namely S, X and D respectively.

**Comment by linuxcaffe** [comment]
oh.. then this request might indeed be overkill. I would rate it as nice-to-have, but not important.
